data:
  calculate_statistics: false
  data_dir: /home/berkay/Desktop/CSIGen/TemporalWiMAE/train_35
  debug_size: null
  normalize: true
  statistics:
    mean_power: 1.4218511784624965e-11
  val_split: 0.1
logging:
  exp_name: temporalenc_beam_factorized_linear_sincat_1x4x4_128d_ffn4x_3blocks8h_2L4h_adamw_cosine_cross_entropy_300ep_bs256_lr5e-4_wd5e-2_beam_oh2_ov2
  log_dir: runs
  log_every_n_steps: 100
  tensorboard: true
model:
  decoder_layers: 2
  decoder_nhead: 4
  embedding:
    type: linear
  encoder_dim: 128
  encoder_layers: 3
  encoder_nhead: 8
  encoder_type: factorized
  input_shape:
  - 14
  - 32
  - 32
  masking:
    num_time_keep: 2
    spatial_mask_ratio: 0.9
    strategy: factorized
  norm_first: false
  patch_size:
  - 1
  - 4
  - 4
  positional_encoding:
    decoder:
      type: sinusoidal_concat
    encoder:
      type: sinusoidal_concat
  type: temporalenc_beam
task:
  beam_prediction:
    antenna_order: hv
    label_mode: snapshot
    n_h: 8
    n_v: 4
    o_h: 2
    o_v: 2
    top_k: 1
training:
  batch_size: 256
  device: cuda:0
  epochs: 200
  gradient_clip_val: 1.0
  loss: cross_entropy
  min_delta: 0.0001
  mixed_precision: true
  num_workers: 4
  optimizer:
    betas:
    - 0.9
    - 0.999
    lr: 0.0005
    type: adamw
    weight_decay: 0.05
  patience: 300
  save_best: true
  save_checkpoint_every_n: 10
  scheduler:
    T_max: 300
    eta_min: 5.0e-06
    type: cosine
    warmup_epochs: 10
